<?php if( !defined('IN_VA') ) exit;

$lang = array(
'Accueil'										=>	'Accueil',
'Accueil_du_site'								=>	'Accueil du site',
'Acheteur'                                      =>  'Acheteur',
'Actif'											=>	'Actif',
'Active'										=>	utf8_encode('Activ�'),
'Action'										=>	'Action',
'Activation_des_comptes'						=>	'Activation des comptes',
'Active'										=>	'Active',
'Administrateur'								=>	'Administarteur',
'Administrateurs'								=>	'Administrateurs',
'Administration'								=>	'Administration',
'Adresse'										=>	'Adresse',
'Afficher_les_dernieres_news'					=>	'Afficher les dernieres news',
'Agence'										=>	'Agence',
'Agence_enregistree'							=>	utf8_encode('Agence enregistr�e'),
'Agence_supprimee'                              =>  utf8_encode('Agence supprim�e'),
'Agences'										=>	'Agences',
'Ajouter'										=>	'Ajouter',
'Ajouter_des_photos'							=>	'Ajouter des photos',
'Ajouter_le'                                    =>  'Ajouter le',
'Ajouter_par'                                   =>  'Ajouter par',
'Ajouter_une_visite'                            =>  'Ajouter une visite',
'Ancien'										=>	'Ancien',
'Annonce'                                       =>  'Annonce',
'Annonces'                                      =>  'Annonces',
'Apercu'										=>	'Aper&ccedil;u',
'Appareil'										=>	'Appareil',
'Arrive'										=>	'Arriv&eacute;',
'Article'										=>	'Article',
'Article_ajoute'								=>	'Article ajout&eacute;',
'Article_modifie'								=>	'Article modifi�',
'Article_supprime'								=>	'Article supprim&eacute;',


'Auteur'										=>	'Auteur',
'Autoriser_upload_image'						=>	'Autoriser l\'upload d\'image',
'Autre'                                         =>  'Autre',
'Autres'                                        =>  'Autres',
'Avatar'										=>	'Avatar',

'Bas'											=>	'Bas',
'Bien'                                          =>	'Bien',
'Bien_supprime'                                 =>  utf8_encode('Bien supprim�'),
'Biens'                                         =>	'Biens',

'Bilan_annuel'									=>	'Bilan annuel',
'Blok'											=>	'Blok',
'Blok_ajoute'									=>	'Blok ajout&eacute;',
'Blok_modifie'									=>	'Blok modifi&eacute;',
'Blok_supprime'									=>	'Blok supprim&eacute',
'Budget'                                        =>  'Budget',
'Cache'											=>	'Cache',
'Cache_supprime'								=>  utf8_encode('Cache supprim�'),


'Categorie'										=>	'Cat&eacute;gorie',
'Categorie_ajoutee'								=>	'Cat&eacute;gorie ajout&eacute;e',
'Categorie_modifiee'							=>	'Cat&eacute;gorie modifi&eacute;e',
'Categorie_supprimee'							=>	'Cat&eacute;gorie supprim&eacute;e',
'Categories'									=>	'Cat&eacute;gories',
'Chambres'										=>	'Chambres',
'Changer_de_mot_de_passe'						=>	'Changer de mot de passe',
'Changement_de_mot_de_passe'					=>	'Changement de mot de passe',
'Choix_du_modele'								=>	'Choix du modele',
'Code'											=>	'Code',
'Code_de_la_video'								=>	utf8_encode('Code de la vid�o'),
'Commentaire'									=>	'Commentaire',
'Commentaire_ajoute'							=>	'Commentaire ajout&eacute;',
'Commentaire_supprime'							=>	'Commentaire supprim&eacute;',
'Compte'                                        =>  'Compte',
'Compte_cree'									=>	'Compte cr&eacute;&eacute;',
'Compte_cree_require_activation_email'			=>	'Votre compte a bien &eacute;t&eacute; cr&eacute;e, un e-mail d&#x27;activation vient d&#x27;&ecirc;tre envoy&eacute;',
'Compte_cree_require_admin'						=>	'Votre compte a bien &eacute;t&eacute; cr&eacute;e, il doit &ecirc;tre activer par un administrateur',
'Compte_rendu'                                  =>  'Compte rendu',
'Compte_rendu_enregistre'                       => utf8_encode('Compte rendu enregistr�'),
'Configuration_enregistree'						=>	'Configuration enregistr&eacute;e',
'Confirm_lock_commentaire'						=>	'Etes vous sur de vouloir bloquer les commentaires de cette news',
'Confirm_unlock_commentaire'					=>	'Etes vous sur de vouloir d&eacute;bloquer les commentaires de cette news',

'Confirm_suppression_article'					=>	'Etes vous sur de vouloir supprimer l\'article',
'Confirm_suppression_bien'						=>	'Etes vous sur de vouloir supprimer ce bien',
'Confirm_suppression_blok'						=>	'Etes vous sur de vouloir supprimer ce blok',

'Confirm_suppression_categorie'					=>	utf8_encode('Etes vous sur de vouloir supprimer cette cat�gorie'),
'Confirm_suppression_commentaire'				=>	'Etes vous sur de vouloir supprimer ce commentaire',

'Confirm_suppression_discussion'				=>	'Etes vous sur de vouloir supprimer cette discussion',


'Confirm_suppression_image'						=>	'Etes vous sur de vouloir supprimer cette image',

'Confirm_suppression_menu'						=>	'Etes vous sur de vouloir supprimer ce menu',
'Confirm_suppression_message'					=>	'Etes vous sur de vouloir supprimer ce message',
'Confirm_suppression_news'						=>	'Etes vous sur de vouloir supprimer cette news',
'Confirm_suppression_page'						=>	'Etes vous sur de vouloir supprimer cette page',
'Confirm_suppression_prospect'                  =>  'Etes vous sur de vouloir supprimer ce prospect',
'Confirm_suppression_photo'                     =>  'Etes vous sur de vouloir supprimer cette photo',
'Confirm_suppression_telechargement'			=>	'Etes vous sur de vouloir supprimer ce t&eacute;l&eacute;chargement',
'Confirm_suppression_utilisateur'				=>	'Etes vous sur de vouloir supprimer cet utilisateur',
'Confirmation'									=>	'Confirmation',
'Consommation_energetique'						=>  utf8_encode('Consommation �nerg�tique'),
'Contact'										=>	'Contact',
'Contact_par_agence'                            =>  'Contact par agence',
'Contact_par_annonce'                           =>  'Contact par annonce',
'Contacter_l_agence'                            =>  'Contacter l\'agence',
'Contenu_page_accueil'							=>	'Contenu accueil',
	
'Constructeur_ajoute'							=>	'Constructeur ajout&eacute;',
'Constructeur_modifie'							=>	'Constructeur modifi&eacute;',

'Contenu'										=>	'Contenu',
'Couleur_du_text'								=>	'Couleur du texte',
'Collaborateur'                                 =>  'Collaborateur',
'Coup_de_coeur'                                 =>  'Coup de coeur',

'Credit'										=>	'Cr&eacute;dit',
'Criteres_de_recherche'                         =>  utf8_encode('Crit�res de recherche'),
'Date'											=>	'Date',
'Date_creation'									=>	'Date de cr&eacute;ation',

'Date_debut'									=>	'Date de d&eacute;but',

'Debit'											=>	'D&eacute;bit',
'Deconnexion'									=>	'Deconnexion',
'Departement'                                   =>  utf8_encode('D�partement'),
'Dernieres_annonces'                            =>  utf8_encode('Derni�res annonces'),
'Dernier_message_le'							=>	'Dernier message le',
'Derniere_visite'								=>	'Derni&egrave;re visite',
'Desactive'										=>	'D&eacute;sactiv&eacute;',
'Description'									=>	'Description',
'Description_du_site'							=>	'Description du site',
'Destinataire'									=>	'Destinataire',

'Detail'										=>	'D&eacute;tail',

'Dim'											=>	'Dim',
'Dimanche'										=>	'Dimanche',
'Directeur'		=>	'Directeur',
'Discussion'									=>	'Discussion',
'Discussion_supprimee'							=>	'Discussion supprim�e',
'Discussions'									=>	'Discussions',

'Droite'										=>	'Droite',

'Edition'										=>	'Edition',
'Edition_agence'                                =>  'Edition agence',
'Edition_article'								=>	'Edition article',

'Edition_menu'									=>	'Edition menu',
'Edition_prospect'                              =>  'Edition prospect',
'Email'											=>	'Email',
'Email_deja_utilise'							=>	'Email deja utilisee',
'Email_envoye_procedure'						=>	'Un email avec la procedure vient d etre envoy&eacute;',
'Emission_ges'									=>	utf8_encode('Emission de gaz � effet de serre'),
'En_attente'									=>	'En attente',
'En_ligne'                                      =>  'En ligne',
'Enregistrement'								=>	'Enregistrement',
'Enregistrer'									=>	'Enregistrer',
'Enregistrer_le'								=>	'Enregistrer le',
'Enregistrement_sur'							=>	'Enregistrement sur',
'Envoyer'										=>	'Envoyer',

'Explication_blok_navigation'					=>	'Pour ajouter des lignes au menu : Nom de votre lien<span style="color:red; font-weight:bold;">|</span>http://votre_lien<span style="color:red; font-weight:bold;">;</span><br/><br/><em>Exemple : Ma page 1|http://adresse_de_votre_site/page/index/1;</em>',
'Explication_prospect_find_biens'               =>  utf8_encode('La recherche de bien n\'a retourner aucune r�ponse. La recherche est effectu�e avec des crit�res strictes. Essayer de reduire les crit�res pour avoir plus de r�sultat!'),
'Explication_taille_video'						=>	utf8_encode('Pour un affichage correcte de la vid�o, elle doit avoir une hauteur (height) de 270px et une largeur (width) de 310px'),
'Fax'		=>	'Fax',
'Fiche'											=>	'Fiche',
'Fichier'										=>	'Fichier',
'Fichier_de_configuration'						=>	'Fichier de configuration',
'Fichier_explication_dl'						=>	'Adresse du fichier : http://www.url.com/lefichier.zip',

'Galerie'										=>	'Galerie',
'Gauche'										=>	'Gauche',
'Generale'										=>	'G&eacute;n&eacute;rale',

'Haut'											=>	'Haut',
'Heure'	=> 'Heure',
'ID_private_calendar'                           =>  'Id du calendrier',
'Identifiant'									=>	'Identifiant',
'Identifiant_deja_utilise'						=>	'Identifiant d&eacute;j&agrave; utulis&eacute;',
'Identification'								=>	'Identification',
'Il_y_a'										=>	'Il y a',
'Information_enregistree'						=>	'Information enregistr�e',
'Image'											=>	'Image',
'Image_actuelle'								=>	'Image actuelle',
'Images_ajoutees'								=>	'Image ajout&eacute;es',
'Immatriculation'								=>	'Immatriculation',
'Impossible_de_supprimer_cette_agence'          =>  'Impossible de supprimer cette agence',
'Indifferent'                                   =>  utf8_encode('Indiff�rent'),
'Indiquer_url_ou_fichier'						=>	'Indiquer l\'url du fichier ou selectionner le fichier a telecharge sur le serveur',
'Infos'											=>	'Infos',

'Jeu'											=>	'Jeu',
'Jeudi'											=>	'Jeudi',
'Jours'											=>	'Jours',
'Jour_de_la_semaine'							=>	'Jour de la semaine',

'le'											=>	'le',

'Libelle'										=>	'Lib&eacute;lle',
'Lien'											=>	'Lien',
'Lien_source'									=>	'Lien source',
'Lier'											=>	'Lier',
'Lier_a_un_telechagement'						=>	'Lier &agrave; un t&eacute;l&eacute;chargement',
'Location'                                      =>  'Location',

    
'Logo'											=>	'Logo',
'Logo_actuel'									=>	'Logo actuel',
'Lu'											=>	'Lu',
'Lun'											=>	'Lun',
'Lundi'											=>	'Lundi',
'Mar'											=>	'Mar',
'Max'                                           =>  'Max',
'Mardi'											=>	'Mardi',
'Marquer_la_scene_installee'					=>	'Marquer la sc&eacute;ne comme install&eacute;e',
'Mer'											=>	'Mer',
'Membre'										=>	'Membre',
'Membres'										=>	'Membres',
'Menu'											=>	'Menu',
'Menu_ajoute'									=>	'Menu ajout&eacute;',
'Menu_modifie'									=>	'Menu modifi&eacute;',
'Menu_supprime'									=>	'Menu supprim&eacute;',
'Mercredi'										=>	'Mercredi',
'Mes_etapes'									=>	'Mes &eacute;tapes',
'Mes_informations'								=>	'Mes informations',
'Mes_pireps'									=>	'Mes PIREPs',
'Mes_scenes'									=>	'Mes sc&eacute;nes',
'Message'										=>	'Message',
'Message_envoye'								=>	'Message envoy&eacute;',
'Message_pirep_refus'							=>	'Bonjour,'."\r\n".'Votre pirep #%d a ete refuse pour la raison suivante : '."\r\n\r\n".'%s',
'Message_supprime'								=>	'Message supprim&eacute;',
'message_non_lus'								=>	'message(s) non lu(s)',
'Methode_envoie_email'							=>	'M&eacute;thode envoie email',
'Min'                                           =>  'Min',
'Modele'										=>	'Mod&egrave;le',
'Modification_effectuee'						=>	'Modification effectu&eacute;e',
'Module_finance'								=>	'Module finance',
'Mois'											=>	'Mois',
'Mon_compte'                                    =>  'Mon compte',
'Montant_commission_vendeur'					=>	'Montant commission vendeur',
'Montant_frais_agence'							=>	'Montant des frais d\'agence',
'Mot_cle'										=>	'Mot cl&eacute;',
'Mot_de_passe'									=>	'Mot de passe',
'Mot_de_passe_change'							=>	'Mot de passe chang&eacute;',
'Mot_de_passe_invalide'							=>	'Mot de passe invalide',
'Mot_de_passe_perdu'							=>	'Mot de passe perdu',
'Navigation'									=>	'Navigation',
'News'											=>	'News',
'News_ajoutee'									=>	'News ajout&eacute;e',
'News_modifiee'									=>	'News modifi&eacute;e',
'News_par_page'									=>	'News par page',
'News_supprimee'								=>	'News supprim&eacute;e',
'News_sur_index'								=>	'Nombre a afficher',
'Nom'											=>	'Nom',	
'Nom_prenom'									=>	'Nom / pr&eacute;nom',
'Nombre_lien_affiche'							=>	'Nombre de lien &agrave; afficher',
'Non'											=>	'Non',
'Nos_agences'                                   =>  'Nos agences',
'Nos_annonces'                                  =>  'Nos annonces',
'Note'											=>	'Note',
'Nous_contacter'                                =>  'Nous contacter',
'Nouveau'										=>	'Nouveau',
'Nouveau_bien'                                  =>  'Nouveau bien',
'Nouveau_menu'									=>	'Nouveau menu',
'Nouveau_prospect'                              =>  'Nouveau prospect',
'Nouvel_article'								=>	'Nouvel article',
'Nouvelle'										=>	'Nouvelle',
'Nouvelle_agence'                               =>	'Nouvelle agence',
'Nouvelle_discussion'							=>	'Nouvelle discussion',

'Nouvelle_page'									=>	'Nouvelle page',
'Nouvelle_visite'                               =>  'Nouvelle visite',
'Ordre'											=>	'Ordre',
'Oui'											=>	'Oui',
'Page'											=>	'Page',
'Page_ajoutee'									=>	'Page ajout&eacute;e',
'Page_modifiee'									=>	'Page modifi&eacute;e',
'Page_supprimee'								=>	'Page supprim&eacute;e',
'Par'											=>	'Par',
'Parking'										=>	'Parking',
'Participant'									=>	'Participant',
'Password'                                      =>  'Mot de passe',
'Pays'                                          =>  'Pays',
'Personne'										=>	'Personne',
'Pieces'										=>	utf8_encode('Pi�ces'),
'Plus'											=>	'Plus',
'Portable'                                      =>  'Portable',
'Position'										=>	'Position',
'Poste_le'										=>	'Post&eacute; le',
'Preference_contact'                            =>  utf8_encode('Pr�f�rence contact'),
'Preference_visite'                             =>  utf8_encode('Pr�f�rence visite'),
'Preferences'									=>	'Pr&eacute;f&eacute;rences',
'Prenom'                                        =>   utf8_encode('Pr�nom'),
'Presentation'									=>	'Presentation',
'Prix'											=>	'Prix',
'Prix_de_vente'									=>	'Prix de vente',
'Profil'										=>	'Profil',
'Profil_modifie'								=>	'Profil modifi&eacute;',
'Proprietaire'                                  =>  utf8_encode('Propri�taire'),
'Prospect'                                      =>  'Prospect',
'Prospect_enregistre'                           =>  utf8_encode('Prospect enregistr�'),
'Prospect_supprime'                             =>  utf8_encode('Prospect supprim�'),
'Prospects'                                     =>  'Prospects',
'Raison'										=>	'Raison',

'Recherche'                                     =>  'Recherche',
'Recherche_en_cour'								=>	'Recherche en cour...',
'Recherche_par'									=>	'Recherche par',
'Rechercher'									=>	'Rechercher',

'Reference'										=>	utf8_encode('R�ference'),
'Refuse'										=>	'Refus&eacute;',
'Repondre'                                      =>  utf8_encode('R�pondre'),
'Requis'										=>	'Requis',
'Resultat'										=>	'R&eacute;sultat',
'Retour'										=>	'Retour',

'S_enregistrer'									=>	'S\'enregistrer',
'Saisie_utilisateur'							=>	'Saisie utilisateur',
'Salle_de_bain'									=>	'Salle de bain',
'Sam'											=>	'Sam',
'Samedi'										=>	'Samedi',
'Scene'											=>	'Sc&eacute;ne',
'Scene_enregistree'								=>	'Scn&eacute;ne enregistr&eacute;e',
'Scene_installee'								=>	'Sc&eacute;ne install&eacute;e',
'Scene_supprimee'								=>	'Sc&eacute;ne supprim&eacute;e',
'Selectionner_position_du_blok'					=>	'Veuillez selectionner la position du blok !',
'Soumis_a_la_direction'							=>	'Soumis &agrave; la direction',
'Source'										=>	'Source',
'Signature'										=>	'Signature',
'Signature_enregistree'							=>	'Signature enregistr�e',
'Simulateur'									=>	'Simulateur',
'Site'											=>	'Site',
'Situation_geographique'                        =>  utf8_encode('Situation g�ographique'),
'Slogan_du_site'                                =>  'Slogan du site',
'Statistique_du_site'							=>	'Statistique du site',
'Status'										=>	'Status',
'Statistique'                                   =>  'Statistique',
'Sujet'											=>	'Sujet',
'Supprimer'										=>	'Supprimer',
'Supprimer_un_lien'								=>	'Supprimer un lien',
'Supprimer_une_agence'                          =>  'Supprimer une agence',
'Surface'										=>	'Surface',
'Suite'											=>	'Suite',
'Systeme'										=>	'Syst&egrave;me',
'Telechargement'								=>	'T&eacute;l&eacute;chargement',
'Telechargement_ajoute'							=>	'T&eacute;l&eacute;chargement ajout&eacute;',
'Telechargement_modifie'						=>	'T&eacute;l&eacute;chagement modifi&eacute;',
'Telechargement_supprime'						=>	'T&eacute;l&eacute;chagement supprim&eacute;',
'Telecharger'									=>	'T&eacute;l&eacute;charger',
'Telephone'										=> utf8_encode('T�l�phone'),
'Texte'                                         =>  'Texte',
'Texte_pied_du_site'							=>	'Texte pied du site',
'Themes'										=>	'Th&egrave;mes',
'Titre'											=>	'Titre',
'Titre_du_site'									=>	'Titre du site',
'Total'											=>	'Total',
'Tout_le_monde'									=>	'Tout le monde',
'Toutes'                                        =>  'Toutes',
'Toutes_les_annonces'                           =>  'Toutes les annonces',
'Tous'											=>	'Tous',
'Transaction'									=>	'Transaction',
'Transferer_les_annonces_vers_agence'           =>  'Transferer les biens sur l\'agence suivante',
'Trouver_une_agence'                            =>  'Trouver une agence',
'Type'											=>	'Type',
'Type_de_bien'                                  =>  'Type de bien',
'Url'											=>	'Url',
'Utilisateur'									=>	'Utilisateur',
'Utilisateur_enregistre'						=>	'Utilisateur enregistr&eacute;',
'Utilisateur_modifie'							=>	'Utilisateur modifi&eacute;',
'Utilisateur_supprime'							=>	'Utilisateur supprim&eacute;',
'Utilisateurs'									=>	'Utilisateurs',
'Validation'									=>	'Validation',
'Validation_etape'								=>	'Validation &eacute;tape',
'Valide'										=>	'Valide',
'Valider'										=>	'Valider',
'Ven'											=>	'Ven',
'Vendredi'										=>	'Vendredi',
'Vendu'                                         =>  'Vendu',
'Vente'                                         =>  'Vente',
'Version'										=>	'Version',
'Vendeur'                                       =>  'Vendeur',
'Ville'											=>	'Ville',
'Visible'										=>	'Visible',
'Visible_par'									=>	'Visible par',
'Visible_seulement_accueil'						=>	'Visible seulement sur la page d\'accueil',
'Visite'                                        =>  'Visite',
'Visites'                                       =>  'Visites',
'Visite_ajoutee'                                =>  utf8_encode('Visite ajout�e'),
'Visiteur'                                      =>  'Visiteur',
'Visiteurs_en_ligne'							=>	'Visiteur en ligne',
'Vitesse_atterissage'							=>	'Vitesse atterrissage',
'Vitesse_verticale_atterisage'					=>	'Vitesse verticale atterrissage',
'Vitesse_de_croissiere'							=>	'Vitesse de croissi&egrave;re',
'Voir'											=>	'Voir',
'Vol'											=>	'Vol',
'Vols'											=>	'Vols',
'Votre_compte_est_active'						=>	'Votre compte est maintenant actif.',
'Votre_email'									=>	'Votre e-mail',
'Votre_mot_de_passe_vient_etre_envoyer'			=>	'Votre nouveau mot de passe vient d etre envoyer par e-mail',
'Vous_avez'										=>	'Vous avez',
'Vous_etes_maintenant_deconnecte'				=>	'D&eacute;connexion.',
'WC'											=>	'WC',
);


$lang['a'] = 'à';
$lang['Amorcage'] = 'Amorçage';
$lang['Annee'] = 'Année';
$lang['au'] = 'au';
$lang['Barque'] = 'Barque';
$lang['Bateau_amorceur'] = 'Barteau armoçeur';
$lang['Bilan'] = 'Bilan';
$lang['Bilan_par_annee'] = 'Bilan par année';
$lang['Bilan_pour_annee'] = 'Bilan pour l\'année';
$lang['Carpbook'] = 'Carpbook';
$lang['Carte'] = 'Carte';
$lang['Carte_de_vos_lieux'] = 'Carte de vos lieux de pêche';
$lang['Caracteres'] = 'Caractères';
$lang['Casse'] = 'Casse';
$lang['Code_postal'] = 'Code postal';
$lang['Confirm_rendre_photo_prive'] = 'Etes vous sur de vouloir rendre privée cette photo';
$lang['Confirm_rendre_photo_public'] = 'Etes vous sur de vouloir rendre publique cette photo';
$lang['Confirm_supression_depart'] = 'Etes vous sur de vouloir supprimer ce départ';
$lang['Confirm_suppression_esche'] = 'Etes vous sur de vouloir supprimer cette esche';
$lang['Confirm_suppression_lieu'] = 'Etes vous sur de vouloir supprimer ce lieu';
$lang['Confirm_supression_photo'] = 'Etes vous sur de vouloir supprimer cette photo';
$lang['Confirm_suppression_poste'] = 'Etes vous sur de vouloir supprimer ce poste';
$lang['Confirm_supression_session'] = 'Etes vous sur de voiloir supprimer cette session';
$lang['Coordonnees_gps'] = 'Coordonnées GPS';
$lang['Date_depart'] = 'Date départ';
$lang['Date_debut'] = 'Date début';
$lang['Date_et_heure'] = 'Date et heure';
$lang['Date_fin'] = 'Date fin';
$lang['Debut'] = 'Début';
$lang['Decroche'] = 'Decroche';
$lang['Depart'] = 'Départ';
$lang['Depart_ajoute'] = 'Départ ajouté';
$lang['Depart_dans_le_temps'] = 'Départ dans le temps';
$lang['Depart_du'] = 'Départ du';
$lang['Depart_modifie'] = 'Départ modifié';
$lang['Depart_supprime'] = 'Départ supprimé';
$lang['Departs'] = 'Départs';
$lang['Dernieres_sessions'] = 'Dernieres sessions';
$lang['Description_50_caracteres_mini'] = 'Votre description doit contenir au minimum 50 caractères';
$lang['Edition_depart'] = 'Edition départ';
$lang['Edition_lieu'] = 'Edition lieu';
$lang['Edition_poste'] = 'Edition poste';
$lang['Edition_session'] = 'Edition session';
$lang['Enduro'] = 'Enduro';
$lang['Enregistre_le'] = 'Enregistré le';
$lang['Erreur_ajout_photo'] = 'Une erreur est survenue durant l\'enregistrement de la photo';
$lang['Esche'] = 'Esche';
$lang['Esche_ajoutee'] = 'Esche ajoutée';
$lang['Esche_modifiee'] = 'Esche modifiée';
$lang['Esche_supprimee'] = 'Esche supprimée';
$lang['Esches'] = 'Esches';
$lang['Explication_depart_public'] = 'Si vous souhaitez que votre prise soit visible par les autres utilisateurs, mettre cette option à <strong>Oui</strong>';
$lang['Explication_perso_esche'] = 'Depuis cette page, vous pouvez ajouter des esches perso.';
$lang['Fiche_de_session'] = 'Fiche de session';
$lang['Flux_rss'] = 'Flux RSS';
$lang['Fin'] = 'Fin';
$lang['Fond'] = 'Fond';
$lang['Gestion_des_esches'] = 'Gestion des esches';
$lang['Gestion_des_lieux'] = 'Gestion des lieux';
$lang['Heure_arrive'] = 'Heure arrivée';
$lang['Heure_de_peche'] = 'Heure de peche';
$lang['Heure_depart'] = 'Heure départ';
$lang['Heure_fin'] = 'Heure fin';
$lang['Identification_requis'] = 'Vous devez être identifié';
$lang['Information_meteo'] = 'Information météo';
$lang['Jour_arrive'] = 'Jour arrivé';
$lang['Jour_fin'] = 'Jour fin';
$lang['Lieu'] = 'Lieu';
$lang['Lieu_ajoute'] = 'Lieu ajouté';
$lang['Lieu_modifie'] = 'Lieu modifié';
$lang['Lieu_supprime'] = 'Lieu supprimé';
$lang['Lieux'] = 'Lieux';
$lang['Logo'] = 'Logo';
$lang['Mes_departs'] = 'Mes départs';
$lang['Mes_sessions'] = 'Mes sessions';
$lang['Meteo'] = 'Meteo';
$lang['Meteo_session'] = 'Météo session';
$lang['Modifier'] = 'Modifier';
$lang['Mon_book'] = 'Mon book';
$lang['Moyenne_depart_session'] = 'Moyenne de depart par session';
$lang['Nombre_depart'] = 'Nombre de départ';
$lang['Nouveau_depart'] = 'Nouveau depart';
$lang['Nouveau_lieu'] = 'Nouveau lieu';
$lang['Nouveau_poste'] = 'Nouveau poste';
$lang['Nouvelle_session'] = 'Nouvelle session';
$lang['Nouvelle_team'] = 'Nouvelle team';
$lang['Orientation'] = 'Orientation';
$lang['Pas_encore_d_esche_perso'] = 'Vous n\'avez pas encore entré d\'esche perso.';
$lang['Pas_encore_depart_pour_cette_session'] = 'Pas encore de départ pour cette cette session';
$lang['Pas_encore_photo'] = 'Pas encore de photo';
$lang['Pas_encore_photos_lieu'] = 'Il n\'y a pas de photos pour ce lieu';
$lang['Pas_encore_photos_poste'] = 'Il n\'y a pas de photos pour ce poste';
$lang['Pas_encore_poste'] = 'Il n\'y a pas encore de poste';
$lang['Pays'] = 'Pays';
$lang['Peche_de_nuit'] = 'Pêche de nuit';
$lang['Phase_lunaire'] = 'Phase lunaire';
$lang['Photo'] = 'Photo';
$lang['Photo_ajoutee'] = 'Photo ajoutée';
$lang['Photo_privee'] = 'Photo privée';
$lang['Photo_publique'] = 'photo publique';
$lang['Photo_supprimee'] = 'Photo supprimée';
$lang['Photos'] = 'Photos';
$lang['Poid'] = 'Poid';
$lang['Poid_moyen'] = 'Poid moyen';
$lang['Poid_total'] = 'Poid total';
$lang['Poisson'] = 'Poisson';
$lang['Poste'] = 'Poste';
$lang['Poste_ajoute'] = 'Poste ajouté';
$lang['Poste_modifie'] = 'Poste modifié';
$lang['Poste_supprime'] = 'Poste supprimé';
$lang['Postes'] = 'Postes';
$lang['Presentation'] = 'Présentation';
$lang['Pression_atmospherique'] = 'Pression atmosphérique';
$lang['Prive'] = 'Privé';
$lang['Public'] = 'Public';
$lang['Recit'] = 'Récit';
$lang['Rendre_photo_prive'] = 'Rendre la photo privée';
$lang['Rendre_photo_publique'] = 'Rendre la photo publique';
$lang['Remonte'] = 'Remonté';
$lang['Record'] = 'Record';
$lang['Repartition_des_departs_par_esches'] = 'Répartition des départs par esches';
$lang['Repartition_des_prises_par_especes'] = 'Répartition des prises par especes';
$lang['Resultat'] = 'Résultat';
$lang['Session'] = 'Session';
$lang['Session_ajoutee'] = 'Session ajoutée';
$lang['Session_du'] = 'Session du';
$lang['Session_modifiee'] = 'Session modifiée';
$lang['Session_supprimee'] = 'Session supprimée';
$lang['Sessions'] = 'Sessions';
$lang['Stats'] = 'Stats';
$lang['Statistique_du_lieu'] = 'Statistique du lieu';
$lang['Taille'] = 'Taille';
$lang['Temperature_air'] = 'Température de l\'air';
$lang['Temperature_eau'] = 'Température de l\'eau';
$lang['Ville'] = 'Ville';
$lang['Visibilite_photo_modifiee'] = 'Visibilité de la photo modifiée';
$lang['Voir'] = 'Voir';
$lang['Vous_devez_selectionner_un_lieu'] = 'Vous devez selectionner un lieu de pêche';

/* - PC - */
$lang['Nord'] = 'Nord';
$lang['Nord_est'] = 'Nord est';
$lang['Nord_ouest'] = 'Nord ouest';
$lang['Est'] = 'Est';
$lang['Ouest'] = 'Ouest';
$lang['Sud'] = 'Sud';
$lang['Sud_est'] = 'Sud est';
$lang['Sud_ouest'] = 'Sud ouest';